/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mysql.Main;

import inventorymanagement.UserDATA;
import inventorymanagement.Users;
import inventorymanagement.myConnection;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author 1styrGroupB
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    PreparedStatement st;
    ResultSet rs;
    public Signup() {
        initComponents();

        
        //center the form
        this.setLocationRelativeTo(null);
        
        // create border for the text and password fields
        Border field_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.black);
        firstnametext.setBorder(field_border);
        lastnametext.setBorder(field_border);
        emailtext.setBorder(field_border);
        passtext.setBorder(field_border);
        confirmtext.setBorder(field_border);
//        rolecombo.setBorder(field_border);
        
        // create a button group for the radiobuttons
        ButtonGroup bg = new ButtonGroup();
        bg.add(male);
        bg.add(female);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fn = new javax.swing.JLabel();
        ln = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        psss = new javax.swing.JLabel();
        confirm = new javax.swing.JLabel();
        emailtext = new javax.swing.JTextField();
        firstnametext = new javax.swing.JTextField();
        lastnametext = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        signup = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        confirmtext = new javax.swing.JPasswordField();
        passtext = new javax.swing.JPasswordField();
        rolecombo = new javax.swing.JComboBox<>();
        exit = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(985, 700));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(51, 51, 255));
        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login-Registration-icon.png"))); // NOI18N
        jLabel2.setText("SIGN UP");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 100, 360, 110);

        gender.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 255));
        gender.setText("Gender:");
        getContentPane().add(gender);
        gender.setBounds(610, 370, 80, 30);

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Inventory Management System");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 20, 390, 110);

        fn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        fn.setForeground(new java.awt.Color(255, 255, 255));
        fn.setText("Firstname:");
        getContentPane().add(fn);
        fn.setBounds(170, 220, 110, 30);

        ln.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ln.setForeground(new java.awt.Color(255, 255, 255));
        ln.setText("Lastname:");
        getContentPane().add(ln);
        ln.setBounds(170, 270, 110, 30);

        email.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email:");
        getContentPane().add(email);
        email.setBounds(210, 320, 62, 30);

        psss.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        psss.setForeground(new java.awt.Color(255, 255, 255));
        psss.setText("Password:");
        getContentPane().add(psss);
        psss.setBounds(170, 370, 110, 30);

        confirm.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        confirm.setForeground(new java.awt.Color(255, 255, 255));
        confirm.setText("Confirm Password:");
        getContentPane().add(confirm);
        confirm.setBounds(90, 420, 190, 30);

        emailtext.setBackground(new java.awt.Color(0, 51, 204));
        emailtext.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        emailtext.setForeground(new java.awt.Color(255, 255, 51));
        emailtext.setBorder(null);
        emailtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtextActionPerformed(evt);
            }
        });
        getContentPane().add(emailtext);
        emailtext.setBounds(290, 320, 210, 30);

        firstnametext.setBackground(new java.awt.Color(0, 51, 255));
        firstnametext.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        firstnametext.setForeground(new java.awt.Color(255, 255, 51));
        firstnametext.setBorder(null);
        firstnametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnametextActionPerformed(evt);
            }
        });
        getContentPane().add(firstnametext);
        firstnametext.setBounds(290, 220, 210, 30);

        lastnametext.setBackground(new java.awt.Color(0, 51, 255));
        lastnametext.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lastnametext.setForeground(new java.awt.Color(255, 255, 51));
        lastnametext.setBorder(null);
        lastnametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnametextActionPerformed(evt);
            }
        });
        getContentPane().add(lastnametext);
        lastnametext.setBounds(290, 270, 210, 30);

        register.setBackground(new java.awt.Color(0, 204, 204));
        register.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        register.setForeground(new java.awt.Color(0, 51, 255));
        register.setText("REGISTER");
        register.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register);
        register.setBounds(400, 500, 210, 40);

        signup.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setText("CompHardware");
        getContentPane().add(signup);
        signup.setBounds(370, 0, 380, 70);

        login.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 51));
        login.setText("Have already an account? LOGIN instead");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(310, 560, 380, 30);

        role.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        role.setForeground(new java.awt.Color(255, 255, 255));
        role.setText("Select Role:");
        getContentPane().add(role);
        role.setBounds(610, 210, 120, 30);

        female.setBackground(new java.awt.Color(204, 255, 255));
        female.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 51));
        female.setText("Female");
        female.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(female);
        female.setBounds(720, 420, 110, 27);

        male.setBackground(new java.awt.Color(204, 255, 255));
        male.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 51));
        male.setText("Male");
        male.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(male);
        male.setBounds(610, 420, 80, 27);

        confirmtext.setBackground(new java.awt.Color(0, 51, 255));
        confirmtext.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        confirmtext.setForeground(new java.awt.Color(255, 255, 51));
        confirmtext.setBorder(null);
        getContentPane().add(confirmtext);
        confirmtext.setBounds(290, 420, 210, 30);

        passtext.setBackground(new java.awt.Color(0, 51, 255));
        passtext.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        passtext.setForeground(new java.awt.Color(255, 255, 51));
        passtext.setBorder(null);
        passtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtextActionPerformed(evt);
            }
        });
        getContentPane().add(passtext);
        passtext.setBounds(290, 370, 210, 30);

        rolecombo.setBackground(new java.awt.Color(0, 51, 255));
        rolecombo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        rolecombo.setForeground(new java.awt.Color(255, 255, 51));
        rolecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inventory Staff", "Cashier" }));
        rolecombo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rolecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolecomboActionPerformed(evt);
            }
        });
        getContentPane().add(rolecombo);
        rolecombo.setBounds(610, 250, 160, 30);

        exit.setBackground(java.awt.Color.red);
        exit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 51));
        exit.setText(" x");
        exit.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white));
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(910, 10, 20, 24);

        minimize.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        minimize.setForeground(java.awt.Color.white);
        minimize.setText(" -");
        minimize.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white));
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize);
        minimize.setBounds(880, 10, 20, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/H.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 700);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstnametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnametextActionPerformed

    private void emailtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtextActionPerformed

    private void lastnametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnametextActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        Users user = new Users();
        user.setFname(firstnametext.getText());
        user.setLname(lastnametext.getText());
        user.setEmail(emailtext.getText());
        user.setPass(passtext.getText());
        user.setRole(rolecombo.getSelectedItem().toString());
        String gender = "Male";
        user.setGender(gender);
        String confirm = String.valueOf(confirmtext.getPassword());
        
         String useremail = emailtext.getText();
        
        if(female.isSelected()){
             gender = "Female";
         }
        
        if(verifyFields()){
            if(!checkUseremail(useremail)){
                UserDATA.save(user);
            }
        }
        
        //show a new form
            dashboard form = new dashboard();
//          form.Ambot.setText(userfield.getText());
            form.setVisible(true);
            form.pack();
            form.setLocationRelativeTo(null);
            // close the current form(login form)
            this.dispose();
        
        
        

    }//GEN-LAST:event_registerActionPerformed

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.red);
        login.setBorder(label_border);
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.lightGray);
        login.setBorder(label_border);
    }//GEN-LAST:event_loginMouseExited

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        Login li = new Login();
        li.setVisible(true);
        li.pack();
        li.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_loginMouseClicked

    private void passtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passtextActionPerformed

    private void rolecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolecomboActionPerformed
      
    }//GEN-LAST:event_rolecomboActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        int e = JOptionPane.showConfirmDialog(null,"Do you really want to exit the from the system?","Select",JOptionPane.YES_NO_OPTION);
        if (e==0){
            System.exit(0);
        }
    }//GEN-LAST:event_exitMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // to miminimize the login frame
        this.setState(Signup.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public boolean verifyFields()
    {
        String fname = firstnametext.getText();
         String lname = lastnametext.getText();
         String email = emailtext.getText();
         String pass = String.valueOf(passtext.getPassword());
         String confirm = String.valueOf(confirmtext.getPassword());
         String role = rolecombo.getSelectedItem().toString();
         String gender = "Male";
        
         // check empty fields
        if(fname.trim().equals("") || lname.trim().equals("") || email.trim().equals("")
           || pass.trim().equals("") || confirm.trim().equals("") || role.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "One Or More Fields Are Empty","Empty Fields",2);
            return false;
    }
         // check if the two password are equals or not
        else if(!pass.equals(confirm))
        {
           JOptionPane.showMessageDialog(null, "Password Doesn't Match","Confirm Password",2); 
           return false;
           
        }
        
        // if everything is ok
        else{
            return true;
        }
    }
    
    public boolean checkUseremail(String useremail){

        boolean useremail_exist = false;
        
        String query = "SELECT * FROM `users` WHERE `Email` = ?";
        
        try {
            
            st = myConnection.getConnection().prepareStatement(query);
            st.setString(1, useremail);
            rs = st.executeQuery();
        
            if(rs.next())
            {
                useremail_exist = true;
                JOptionPane.showMessageDialog(null, "This Email is Already Taken,\n Choose Another One", "Email Failed", 2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return useremail_exist;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }
    
    // create a function to check if the entered username already exists in the database
// 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirm;
    private javax.swing.JPasswordField confirmtext;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailtext;
    private javax.swing.JLabel exit;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField firstnametext;
    private javax.swing.JLabel fn;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField lastnametext;
    private javax.swing.JLabel ln;
    private javax.swing.JLabel login;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel minimize;
    private javax.swing.JPasswordField passtext;
    private javax.swing.JLabel psss;
    private javax.swing.JButton register;
    private javax.swing.JLabel role;
    private javax.swing.JComboBox<String> rolecombo;
    private javax.swing.JLabel signup;
    // End of variables declaration//GEN-END:variables
}
